from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('course/<int:course_id>/lectures/', views.lecture, name='lecture'),
    path('admin_log/', views.mlog, name='mlog'),
    path('instructor/', views.in_register, name='in_register'),
    path('list/', views.course_list, name='course_list'),
    path('create/', views.course_create, name='course_create'),
    path('enroll/<int:course_id>/', views.enroll_course, name='enroll'),
    path('signin/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('register/', views.register, name='register'),
    path('add/', views.add_course, name='add_course'),
    path('course/<int:course_id>/details/', views.details, name='details'),
    path('course/<int:course_id>/payment/', views.course_payment, name='course_payment'),
    path('profile/', views.profile_view, name='profile'),
    path('user_dashboard/', views.student, name='student'),
    path('lesson/lecture/delete/<int:lecture_id>/', views.delete_lecture, name='delete_lecture'),
    path('edit_lecture/<int:lecture_id>/', views.edit_lecture, name='edit_lecture'),
    # path('quizzes/', views.quiz_list, name='quiz_list'),
    path('quiz/<int:quiz_id>/', views.quiz_detail, name='quiz_detail'),
    path('quiz/<int:quiz_id>/submit/', views.submit_quiz, name='submit_quiz'),
    path('admin_register/', views.admin_register, name='admin_register'),
    path('admin_dashboard/', views.admin, name='admin'),
    path('course/', views.courses, name='course'),
    path('course/delete/<int:course_id>/', views.delete_course, name='delete_course'),
    path('edit_course/<int:course_id>/', views.edit_course, name='edit_course'),
    path('category/', views.add_category, name='add_category'),
    path('category/delete/<int:category_id>/', views.delete_category, name='delete_category'),
    path('lesson/', views.lesson_ad, name='lessons'),
    path('add_lesson/', views.add_lesson, name='add_lesson'),
    path('enrollment/', views.enrollment, name='enrollment'),
    path('add_enroll/', views.add_enroll, name='add_enroll'),
    path('enrollment/delete/<int:enrollment_id>/', views.delete_enroll, name='delete_enroll'),
    path('candidate/', views.candidate_pf, name='profiles'),
    path('add_user/', views.add_profile, name='add_profile'),
    path('quiz/', views.quiz_ad, name='quiz'),
    path('add_quiz/', views.add_quiz, name='add_quiz'),
    path('add_question/', views.add_question, name='add_question'),
    path('add_choice/', views.add_choice, name='add_choice'),
    path('quiz/delete/<int:quiz_id>/', views.delete_quiz, name='delete_quiz'),
    path('question/delete/<int:question_id>/', views.delete_question, name='delete_question'),
    path('choice/delete/<int:choice_id>/', views.delete_choice, name='delete_choice'),
    path('quiz_attempt/', views.qu_attempt, name='attempt'),
    path('add_attempt/', views.add_attempt, name='add_attempt'),
    path('add_use/', views.add_use, name='add_use'),
    path('attempt/delete/<int:attempt_id>/', views.delete_attempt, name='delete_attempt'),
    path('use/delete/<int:use_id>/', views.delete_use, name='delete_use'),
    path('detail/', views.course_detail, name='course_detail'),
    path('add_detail/', views.add_detail, name='add_detail'),
    path('edit_detail/<int:detail_id>/', views.edit_detail, name='edit_detail'),
    path('detail/delete/<int:detail_id>/', views.delete_detail, name='delete_detail'),
    path('certificate/', views.certification, name='certificate'),
    path('add_certificate/', views.add_certificate, name='add_certificate'),
    path('edit_certificate/<int:certificate_id>/', views.edit_certificate, name='edit_certificate'),
    path('certificate/delete/<int:certificate_id>/', views.delete_certificate, name='delete_certificate'),
    path('edit_quiz/<int:quiz_id>/', views.edit_quiz, name='edit_quiz'),
    path('edit_question/<int:question_id>/', views.edit_question, name='edit_question'),
    path('edit_choice/<int:choice_id>/', views.edit_choice, name='edit_choice'),
    path('quiz/result/<int:attempt_id>/', views.quiz_result, name='quiz_result'),
    path('lecture/<int:lecture_id>/mark_video/', views.mark_video_watched, name='mark_video'),
    path('lecture/<int:lecture_id>/mark_pdf/', views.mark_pdf_viewed, name='mark_pdf'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('quiz_st/', views.quiz_st, name='quiz_st'),
    path('edit_profile/<int:profile_id>/', views.edit_profile, name='edit_profile'),
    path('candidate/delete/<int:profile_id>/', views.delete_candidate, name='delete_candidate'),
    path('quiz_in/', views.quiz_instructor, name='quiz_instructor'),
    path('search/', views.search_courses, name='search_courses'),
    path('courses/sorted/', views.sorted_course, name='sorted_courses'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)